language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t sundarsingh/react-test -f ./client/DockerFile.dev ./client
script:
  - docker run -e CI=true sundarsingh/react-test npm run test

after_success:

  - docker build -t sundarsingh19/multi-client ./client
  - docker build -t sundarsingh19/multi-nginx ./nginx
  - docker build -t sundarsingh19/multi-server ./server
  - docker build -t sundarsingh19/multi-worker ./worker
  # Log in to the docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take those images and push to docker hub

  - docker push sundarsingh19/multi-client
  - docker push sundarsingh19/multi-nginx
  - docker push sundarsingh19/multi-server
  - docker push sundarsingh19/multi-worker

  # finished pushing images

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-051675516925
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
